version: "3" # Docker Compose 文件版本

services:
  nginx:
    image: nginx:latest # 使用最新的 nginx 镜像
    container_name: web-swmm-nginx # 设置容器名称
    ports:
      - 9030:80 # 将容器的80端口映射到宿主机的80端口
    volumes:
      - ./docker-volumes/nginx/html:/usr/share/nginx/html # 映射静态文件目录
      - ./docker-volumes/nginx/nginx.conf:/etc/nginx/nginx.conf # 映射 nginx 配置文件
      # - /home/web-swmm/docker-volumes/nginx/html:/usr/share/nginx/html
      # - /home/web-swmm/docker-volumes/nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - web-swmm_network # 连接到自定义网络
    restart: always # 容器退出后总是重启
  fastapi:
    image: web-swmm:latest # 使用构建的最新 FastAPI 镜像
    container_name: web-swmm-fastapi # 设置容器名称
    build: . # 从当前目录构建镜像
    ports:
      - 9033:8080 # 将容器的8080端口映射到宿主机的9013端口
    volumes:
      - ./docker-volumes/swmm:/app/backend/swmm # 映射 后端 swmm 目录
      # - /home/web-swmm/docker-volumes/swmm:/app/backend/swmm
    networks:
      - web-swmm_network # 连接到自定义网络
    restart: always # 容器退出后总是重启

  postgres:
    image: postgres:15 # 指定具体版本
    container_name: web-swmm-postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      TZ: Asia/Shanghai # 设置时区
    ports:
      - "9034:5432"
    volumes:
      - ./backend/static/pgdata_volume:/var/lib/postgresql/data # 本地挂载
    networks:
      - web-swmm_network
    restart: unless-stopped
    command: ["postgres", "-c", "max_connections=200"] # 自定义配置

networks:
  web-swmm_network:
    driver: bridge # 使用 bridge 网络驱动
