version: "3.8"

services:
  postgres:
    image: postgres:15 # 指定具体版本
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      TZ: Asia/Shanghai # 设置时区
    ports:
      - "15432:5432"
    volumes:
      - ./backend/static/pgdata_volume:/var/lib/postgresql/data # 本地挂载
    restart: unless-stopped
    command: ["postgres", "-c", "max_connections=200"] # 自定义配置
